name: party_weather
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  uno: ^1.1.9
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true
