name: party_weather
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  geolocator: ^10.0.0
  uno: ^1.1.9
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  freezed: ^2.4.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
